export default {
    BALANCE_REQUEST : "BALANCE_REQUEST",
    BALANCE_COMPLETED : "BALANCE_COMPLETED",
    BALANCE_FAILED : "BALANCE_FAILED",

    USER_TOKEN_COMPLETED:"USER_TOKEN_COMPLETED",
    USER_TOKEN_FAILED:"USER_TOKEN_FAILED",

    LOGOUT:"LOGOUT",

    AVAILABLE_PLANS_COMPLETED:"AVAILABLE_PLANS_COMPLETED",
    AVAILABLE_PLANS_FAILED:"AVAILABLE_PLANS_FAILED",
    AVAILABLE_PLANS_REQUEST:"AVAILABLE_PLANS_REQUEST",

    ACTIVE_USERS_COMPLETED:"ACTIVE_USERS_COMPLETED",
    ACTIVE_USERS_FAILED:"ACTIVE_USERS_FAILED",

    PAYMENTS_STATUS_COMPLETED:"PAYMENTS_STATUS_COMPLETED",
    PAYMENTS_STATUS_FAILED:"PAYMENTS_STATUS_FAILED",
    PAYMENTS_STATUS_REQUEST:"PAYMENTS_STATUS_REQUEST",
}